return {
  {
    "LazyVim/LazyVim",
    opts = {
      -- icons used by other plugins
      icons = {
        diagnostics = {
          -- Error = "󱈸",
          -- Warn = "",
          Error = "󱈸",
          Warn = "󱈸",
          Hint = "󱠃",
          Info = "ℹ",
        },
        git = {
          -- added = " ",
          added = "󱇬 ",
          -- modified = " ",
          modified = "󰲶 ",
          -- removed = " ",
          removed = "󱘹 ",
        },
        kinds = {
          Array = " ",
          Boolean = " ",
          Class = " ",
          Color = " ",
          Constant = " ",
          Constructor = " ",
          Copilot = " ",
          Enum = " ",
          EnumMember = " ",
          Event = " ",
          Field = " ",
          File = " ",
          Folder = " ",
          Function = " ",
          Interface = " ",
          Key = " ",
          Keyword = " ",
          Method = " ",
          Module = " ",
          Namespace = " ",
          Null = "ﳠ ",
          Number = " ",
          Object = " ",
          Operator = " ",
          Package = " ",
          Property = " ",
          Reference = " ",
          Snippet = " ",
          String = " ",
          Struct = " ",
          Text = " ",
          TypeParameter = " ",
          Unit = " ",
          Value = " ",
          Variable = " ",
        },
      },
    },
  },
}
